### ISSUE TITLE
AWS tags for PVCs

### ISSUE THREAD

**Issue by MilanDasek** [kubernetes-sigs/aws-ebs-csi-driver#1014]
Hello,

Is it possible to add PVC tag annotation(s), which would be picked by the driver and added to particular EBS volume - like this tool does - https://github.com/mtougeron/k8s-aws-ebs-tagger

I mean to be able to tag individual volumes, on top of "same tags for all" like it is supported now.

Thank you.

**Comment by wongma7** [comment]
no, because the driver only knows the PVC namespace/name and PV name. It might be possible in future but would require changes in our dependency  https://github.com/kubernetes-csi/external-provisioner/blob/74d3c4c26f3d9115f6c157dd81c4594025daeb0a/pkg/controller/controller.go#L690-L695

Also there are some security/permission issues with letting PVC user dictate tags but I understand that's a tradeoff most people are willing to make.

**Comment by robbie-demuth** [comment]
+1 to this as a feature request. Being able to tag EBS volumes / snapshots based on labels / annotations on Kubernetes resources would be extremely helpful for enabling cross-cluster restores w/out having to teach external systems to record persistent volume or volume snapshot content names

**Comment by mikesir87** [comment]
I, too, am interested in this feature and can provide a little bit of additional context on our use case. 

We are running multi-tenant EKS clusters where we create various node pools for cost accounting (each pool gets the appropriate cost accounting tags applied). To simplify billing, we'd like to also attach the same tags to the EBS resources created for those tenants. We have the ability to perform mutations (which is how we do pod assignment to the correct pool) and would like to mutate on annotations to the PVCs that would appear as additional tags on the volume.
