### ISSUE TITLE
Unable to create PVC from snapshot if G is used as size instead of Gi

### ISSUE THREAD

**Issue by manosoft** [kubernetes-sigs/aws-ebs-csi-driver#1023]
/kind bug

**What happened?**
I want to clone my existing application for test purpose.
I'm following below steps

Create snapshot of existing PVC
Create PVC from snapshots
Start clone application using PVC from step 2
At step 2, I see below error and PVC creation fails.

failed to provision volume with StorageClass "ebs-sc": error getting handle for DataSource Type VolumeSnapshot by Name snap001: requested volume size 1000000000 is less than the size 1073741824 for the source snapshot snap001

**What you expected to happen?**
We should be able to create PVC from Volume Snapshot.

**How to reproduce it (as minimally and precisely as possible)?**
Run below commands using attached yamls.

kubectl create -f 00-create-namespace.yaml
kubectl create -f 01-pvc-create.yaml
kubectl create -f 02-pod-create.yam
kubectl create -f 03-snapshot.yaml
kubectl create -f 04-pvc-from-snapshot.yaml
kubectl create -f 05-pod-clone.yaml

Please edit 01-pvc-create.yaml 03-snapshot.yaml 04-pvc-from-snapshot.yaml files with appropriate storageclass and volumesnapshotclass.
[00-create-namespace.yaml.txt](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/files/6980885/00-create-namespace.yaml.txt)
[01-pvc-create.yaml.txt](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/files/6980886/01-pvc-create.yaml.txt)
[02-pod-create.yaml.txt](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/files/6980881/02-pod-create.yaml.txt)
[03-snapshot.yaml.txt](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/files/6980882/03-snapshot.yaml.txt)
[04-pvc-from-snapshot.yaml.txt](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/files/6980883/04-pvc-from-snapshot.yaml.txt)
[05-pod-restore.yaml.txt](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/files/6980884/05-pod-restore.yaml.txt)

**Anything else we need to know?**:
This should be easily reproducible on any AWS EKS version with above mentioned repro steps.

**Environment**
- Kubernetes version (use `kubectl version`): "v1.20.7-eks-d88609"
- Driver version: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/release-1.0

```
 k get volumesnapshot -nsnap-test
NAME      READYTOUSE   SOURCEPVC   SOURCESNAPSHOTCONTENT   RESTORESIZE   SNAPSHOTCLASS   SNAPSHOTCONTENT                                    CREATIONTIME   AGE
snap001   true         my-pvc                              1Gi           csi-aws-vsc     snapcontent-445205fb-f3e5-4d0a-b10a-9240ee7a843c   38h            38h
```

**Comment by vdhanan** [comment]
to clarify, are you expecting G and Gi to be the same size?

**Comment by manosoft** [comment]
No, I expect PVC creation from VolumeSnapshot to be successful if I use G as size.

**Comment by nirmalaagash** [comment]
@manosoft When you create a pod using `kubectl create -f 02-pod-create.yaml`, the volume that gets assigned is 1Gi instead of G. It is because the [CreateVolume](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVolume.html) API expects size in terms of GiB (integers), thus the size is rounded off to GiB before the request is made. This makes the `RESTORESIZE` of snapshot from PVC to be 1Gi.
When PVC from snapshot is created, the validation is done in the `external-provisioner` [sidecar](https://github.com/kubernetes-csi/external-provisioner/blob/0456e7315a07228c16360a57a611aa0a1279fcdc/pkg/controller/controller.go#L1100) before rounding off the size and hence you see that error.
Please provide a storage size equal to or greater than the `RESTORESIZE` of snapshot for it to run with no error.
