### ISSUE TITLE
Outdated e2fsck?

### ISSUE THREAD

**Issue by shapirus** [kubernetes-sigs/aws-ebs-csi-driver#1110]
/kind bug

**What happened?**
I am seeing the following messages in the ebs-plugin container logs:

```
2021-11-10T13:44:41+02:00       e2fsck: Get a newer version of e2fsck!
2021-11-10T13:44:41+02:00       /dev/nvme4n1 has unsupported feature(s): metadata_csum
2021-11-10T13:44:41+02:00       I1110 11:44:41.883562       1 mount_linux.go:353] `fsck` error fsck from util-linux 2.30.2
```

**Environment**
AWS

- Kubernetes version (use `kubectl version`):
1.21.5

- Driver version:
1.4.0

**Comment by victorcq** [comment]
We got the same logs, we fixed it by building our own driver image - changed it from using Amazon Linux 2 base image to Amazon Linux 2022 base image (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/Dockerfile#L29). It appears that Amazon Linux 2022 base image has got newer `e2fsprogs` package (https://github.com/aws/eks-distro-build-tooling/blob/main/eks-distro-base-minimal-packages/2022/linux_amd64/csi-ebs#L4). Not 100% sure if it's safe to use the AL2022 base image tough, because AL2022 is not officially GA yet. 

**Environment**
AWS self managed cluster
Kubernetes version: 1.22
Driver version: 1.12.1

**Comment by shapirus** [comment]
@stardevq please post the updated details of what you are experiencing, if it is any different from what is shown in the original post.

**Comment by hanyuel** [comment]
@stardevq can you please also add repro steps? Thanks

**Comment by AndrewSirenko** [comment]
We have upgraded our Linux Base image from AL2 to AL2023 in driver v1.23.0. I believe this should resolve this issue. Thank you for your insights and feel free to re-open this issue if you are not satisfied. 

/close
