### ISSUE TITLE
EBS drive memory usage is too high

### ISSUE THREAD

**Issue by okt2019** [kubernetes-sigs/aws-ebs-csi-driver#1181]
1、After using the EBS drive in EKS for a period of time, it is found that the pod memory usage is gradually increasing, as follows：
kubectl top pods -n kube-system 
NAME                                                       CPU(cores)   MEMORY(bytes)             
ebs-csi-controller-b87964fbc-jtglj              2m           196Mi           
ebs-csi-controller-b87964fbc-nfbnm         2m           6157Mi  
ebs-csi-node-2nq5d                                     1m           165Mi           
ebs-csi-node-4svq7                                      1m           5134Mi

2、If the memory usage is too high, how should I troubleshoot it, or what is the general cause?

3、I just used prometheus and grafana to monitor the EKS performance of this EBS drive. At the beginning, the resource usage was relatively low. After a period of time, the memory usage increased.

**Comment by os6sense** [comment]
I'm disappointed this question hasn't been answered. We're currently seeing 5GB memory used per node, which seems unreasonable; I assume this is due to caching but maybe not.

**Comment by torredil** [comment]
Hi, thanks for raising up this issue.

We have not been able to reproduce this on our end. Could you please specify which version of the driver you are running and provide any relevant logs you are able to collect when running into this issue?

It's possible that this abnormal memory usage was caused by outdated sidecar images. The sidecars have now been updated with the release of `v1.6.2`. If you are able to, I recommend updating the driver to the latest version which could potentially fix this issue.

**Comment by bhushanchirmade** [comment]
We are using following Terraform code to pull the latest version of the add-on and seeing only 1.6.1. 

data "aws_eks_addon_version" "aws-ebs-csi-driver" {
  addon_name         = "aws-ebs-csi-driver"
  kubernetes_version = "1.22"
  most_recent        = true
}

output "ebs_version" {
  value = data.aws_eks_addon_version.aws-ebs-csi-driver.version
}

Deployment of this add-on is using these versions.
        image: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/aws-ebs-csi-driver:v1.6.1
        image: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/csi-provisioner:v2.2.2
        image: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/csi-attacher:v3.1.0
        image: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/csi-snapshotter:v3.0.3
        image: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/csi-resizer:v1.1.0
        image: 602401143452.dkr.ecr.us-east-1.amazonaws.com/eks/livenessprobe:v2.4.0

Please let us know if there is any other way to pull the version 1.6.2

**Comment by torredil** [comment]
The add-on release for `v1.6.2` has been delayed due to an internal AWS process. We are currently working with the EKS team to release a new version of the add-on which patches the CVE and increases the memory limit from 128MB -> 256MB to address the memory issue discussed here https://github.com/aws/containers-roadmap/issues/1757.

**Comment by bhushanchirmade** [comment]
Can anybody from EKS team comment here about the release of `v1.6.2` version?

**Comment by torredil** [comment]
If you are experiencing a memory issue, upgrade the driver to [v1.7.0](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG.md#announcement)+
