### ISSUE TITLE
PersistentVolumes in terminating state after migration

### ISSUE THREAD

**Issue by czomo** [kubernetes-sigs/aws-ebs-csi-driver#1298]
/kind bug

**What happened?**
I've updated my k8s  from 1.21.12 to 1.22.11 using kops along with adding csi migration. 9 of 125 PV went into `Terminating` state and couldn't attach volume. EBS stayed intact hence I could recover from failure.
Annotation of pv
```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: aws-ebs-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/migrated-to: ebs.csi.aws.com
    pv.kubernetes.io/provisioned-by: kubernetes.io/aws-ebs
```

PersistentVolume
```
k get pv pvc-aea5fa6f-8227-11e9-a63e-02fb3c494a38
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS        CLAIM                                                 STORAGECLASS   REASON   AGE
pvc-aea5fa6f-8227-11e9-a63e-02fb3c494a38   16Gi       RWO            Delete           Terminating   namespaece/data   gp2                     3y37d
```

Volumeattachment
```
k get volumeattachments.storage.k8s.io csi-f83c286a6391396c0c96b22f038a4107253876d547676ca982a73422092489b0
NAME                                                                   ATTACHER          PV                                         NODE                                        ATTACHED   AGE
csi-f83c286a6391396c0c96b22f038a4107253876d547676ca982a73422092489b0   ebs.csi.aws.com   pvc-aea5fa6f-8227-11e9-a63e-02fb3c494a38   ip-10-160-x-x.us-west-2.compute.internal   false      10h
```

Message from pod
```
Warning  FailedAttachVolume  5m52s (x79 over 151m)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-aea5fa6f-8227-11e9-a63e-02fb3c494a38" : PersistentVolume "pvc-aea5fa6f-8227-11e9-a63e-02fb3c494a38" is marked for deletion      
```
**What you expected to happen?**
After migration all PV should be migrated without downtime. No manual work required to patch. This breaking workflow on *production * clusters.

**How to reproduce it (as minimally and precisely as possible)?**
Use aws-ebs-csi-driver v1.5.0 with k8s 1.22.11. Kops 1.23.2 enable feature gates:
```
                            +   featureGates:
                            +     CSIMigrationAWS: "true"
                            +     InTreePluginAWSUnregister: "true"
```

**Anything else we need to know?**:
Workaround:
1. Edit pv - by setting Retain policy ebs should stay intact after removing pv/pvc - IMPORTANT CHECK IF PATCHED
`kubectl patch pv pv-name -p '{"spec":{"persistentVolumeReclaimPolicy":"Retain"}}'`
2. Scale pods using that pvc to 0
3. BACKUP pv and pvc with neat to obfuscate irrelevant data
`kubectl get pv -o yaml pv-name |kubectl neat`
`kubectl get pvc -o yaml name-pvc |kubectl neat`
4. Delete pvc and check if pv is also remover
5. Apply persistentVolume backup(step 3), then persistentVolumeClaim
6. Fix deadlock for pv because of existing claim
`kubectl patch pv pv-name -p '{"spec":{"claimRef": null}}'`

**Environment**
- Kubernetes version (use `kubectl version`): 1.22.11
- Driver version: v1.5.0

**Comment by torredil** [comment]
Hey, thanks for raising this up. My understanding is that when deleting a PVC, the corresponding PV gets "released". Since the PV may contain sensitive data, it should not be used again without admin intervention for security reasons- even if a PVC object with the same name/namespace is present.

An admin has two options:
- Make the PV available to everybody - `kubectl patch pv my-pv-name -p '{"spec":{"claimRef": null}}'`. This will delete the existing claim and will make the PV available to any PVC that matches the capacity, access mode, and selectors specified. 
- Make the PV available to a specific PVC - pre-fill `PV.Spec.ClaimRef` with a pointer to a PVC. 

**Warning** 
- Removing `claimRef` (or setting it to null) will cause the volume the be immediately removed if the [reclaim policy](https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/) is set to `Delete`. **Please ensure the reclaim policy has been patched**: `kubectl describe pv pv-name | grep -e Reclaim`.
- Removing `claimRef` (or setting it to null) will make the PV "available" to any PVC meeting the criteria.

**Comment by czomo** [comment]
> My understanding is that when deleting a PVC, the corresponding PV gets "released". 

Yeah I got you, I could edit pv PV.Spec.ClaimRef obtained in step 3 of my workaround. Then I wouldn't need to patch it later. And yes this is risky operation, that's why i mention to check it twice.

The thing that is worth to point out is that  faulty pv have `Finalizers:        [[kubernetes.io/pv-protection](http://kubernetes.io/pv-protection)]` instead of `Finalizers:        [[kubernetes.io/pv-protection](http://kubernetes.io/pv-protection) external-attacher/ebs-csi-aws-com]`. That's why I get the idea to recreate pv.
