### ISSUE TITLE
After deleting the aws-ebs-csi-driver to PVC still will add wrong annotations

### ISSUE THREAD

**Issue by asahnovskiy-deloitte** [kubernetes-sigs/aws-ebs-csi-driver#1393]
/kind bug

**What happened?**
I installed aws-ebs-csi-driver via helm chart. Tested app and removed.  Now when I try to create PVC  with another StorageClass (manually or when I install other app via helm) all PVC have
 annotations:
    volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
    volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com

and I get the issue:
waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator

**What you expected to happen?**

PVC will be created without annotations or how I can delete aws-ebs-csi-driver ?

**Environment**
- Kubernetes version (use `kubectl version`): 1.23.7
- Driver version:  version: 2.8.1 of helm

**Comment by ConnorJC3** [comment]
Hi @asahnovskiy-deloitte. It sounds like you are still using a StorageClass setup for use with the EBS CSI Driver. While uninstalling will delete any StorageClasses that we created, it will not delete SCs that you created for the driver. Make sure to delete any SC with the `provisioner` field set to `ebs.csi.aws.com`.

You will need to refer to the documentation of whatever new driver you are using (such as the EFS CSI Driver) for information on how to create and use an appropriate StorageClass for it (if you are instead trying to use an in-tree volume provider, refer to the kubernetes documentation instead).

**Comment by asahnovskiy-deloitte** [comment]
@ConnorJC3  I have
kubectl get sc
NAME                      PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
gp2                                  kubernetes.io/aws-ebs   Delete          WaitForFirstConsumer   false                  2d16h
gp2-encrypted (default)   kubernetes.io/aws-ebs   Retain          Immediate                     true                   6h25m
 
I don't see any SC with ebs.csi.aws.com provisioner

**Comment by asahnovskiy-deloitte** [comment]
k describe pvc test-pvc
Name:          test-pvc
Namespace:     default
StorageClass:  gp2-encrypted
Status:        Pending
Volume:
Labels:        app=test-pvc
Annotations:   volume.beta.kubernetes.io/storage-provisioner: ebs.csi.aws.com
               volume.kubernetes.io/storage-provisioner: ebs.csi.aws.com
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type    Reason                Age                      From                         Message
  ----    ------                ----                     ----                         -------
  Normal  ExternalProvisioning  2m45s (x1465 over 6h7m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "ebs.csi.aws.com" or manually created by system administrator

**Comment by ConnorJC3** [comment]
This is probably due to CSI Migration. Kubernetes is moving away from in-tree volume plugins, and thus redirecting the old in-tree requests to their CSI Driver equivalent: https://kubernetes.io/blog/2021/12/10/storage-in-tree-to-csi-migration-status-update/

If you are on EKS, the relevant documentation is here: https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi-migration-faq.html (in short, EKS no longer supports the in-tree plugin * at all* in kubernetes 1.23+, and the EBS CSI Driver is required to use EBS volumes).

If you are using a self-hosted cluster, you can disable this functionality by disabling the `CSIMigrationAWS` feature gate on your cluster, but I should warn that feature gate has been moved to GA (and thus force-enabled) as of kubernetes 1.25: https://github.com/kubernetes/kubernetes/pull/111479
