### ISSUE TITLE
[helm] Don't check capabilities when `enableMetrics: true`

### ISSUE THREAD

**Issue by z0rc** [kubernetes-sigs/aws-ebs-csi-driver#1420]
/kind bug

**What happened?**
ServiceMonitor resource is guarded behind the `.Capabilities.APIVersions.Has` check. https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1380/files#diff-2412b20598542fa98f5a07543074554a7ca2bf9fa414b35e7cbc83a429f3c142R19

This check is problematic, as in order to resolve it `helm template` should be executed with `--validate` flag and connect to cluster that has CRDs installed.

**What you expected to happen?**
I would strongly prefer to have `.Capabilities.APIVersions.Has` check dropped or replaced with user settable value, like `serviceMonitor: true`

**How to reproduce it (as minimally and precisely as possible)?**
Try to install this chart with `enableMetrics: true` and cluster that *doesn't* have prometheus-operator CRDs installed. I would strongly prefer to see helm error, that ServiceMonitor is unknown resource kind, instead of having it skipped and chart installed.

**Anything else we need to know?**:
`.Capabilities.APIVersions.Has` is good to deal with kubernetes native resources that have multiple versions available, like `policy/v1` and `policy/v1beta1`. In most cases this function can be successfully resolved without need to connect to cluster. But it isn't suitable to check CRDs availability, where installation failure is desirable outcome instead of having resource silently omitted.

**Environment**
- Kubernetes version (use `kubectl version`): 1.23
- Driver version: v1.12.0

CC @torredil

**Comment by ConnorJC3** [comment]
I strongly believe we should leave `enableMetrics` as is. As it currently is, we could add support for other metrics collection systems in the future under the `enableMetrics` option, so that it always just attempts to do the right thing. If we instead make this change, we lock ourselves into supporting only "ServiceMonitors for the Prometheus Operator".

We could add a secondary option to forcefully render the ServiceMonitor under all circumstances, but I'm not sure I understand the need:
1. `helm template` users can use the flag `--api-version monitoring.coreos.com/v1`
2. It should be immediately obvious to users what's going on when they realize they don't even have the prometheus operator installed, so is there a significant advantage to adding an option to crash out early when applying the helm chart?

**Comment by z0rc** [comment]
1. Adding `--api-versions` isn't that trivial or obvious, especially when `helm template` is executed under the hood of several CD tools, like `helmfile` for instance.
2. Yes

> I strongly believe we should leave enableMetrics as is.

That's why I proposed "or replaced with user settable value". Either of options is good for me.
