### ISSUE TITLE
Adding extra tags to existing EBS volumes

### ISSUE THREAD

**Issue by njuettner** [kubernetes-sigs/aws-ebs-csi-driver#1438]
/triage support

Is there a way to add tags to EBS volumes which are already created by ebs-csi-controller? AFAIK when adding the extraTags flag it only considers those when creating a new volume.

**Comment by torredil** [comment]
Volume tags via `StorageClass.parameters` or the `extraTags` flag are specified when creating a new volume. There is no mechanism in the driver for adding extra tags to existing EBS volumes. 

A solution here would be using the [EC2 API](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/create-tags.html) to tag an already existing resource: 
`aws ec2 create-tags --resources $resource_id --tags Key=Stack,Value=production`

**Comment by dudicoco** [comment]
@torredil can you please elaborate why is this the wanted behavior and why was this ticket closed?
A controller's purpose is to have a control loop and adjust the actual state to the desired state, according to that logic the AWS EBS CSI Controller should modify the state of the volume, including its tags whenever the desired state changes.

**Comment by torredil** [comment]
Hi @dudicoco, today StorageClass parameters are immutable by design which limits the driver's ability to do the above. The good news is this may be possible to support in the near future via https://github.com/kubernetes/enhancements/issues/3751. I encourage you to open a new feature request for this using the provided [template](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/new?assignees=&labels=&projects=&template=feature_request.md) and we can go into more detail there, thank you!

**Comment by dudicoco** [comment]
Thanks for the info @torredil, makes sense.

Perhaps a workaround would be to add support for tags in PVC annotations?
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/modify-volume.md
