### ISSUE TITLE
Reusing dynamically provisioned EBS volumes with AWS EBS CSI driver after recreating EKS cluster

### ISSUE THREAD

**Issue by kuppuswamy** [kubernetes-sigs/aws-ebs-csi-driver#1451]
/triage support

Is there a way to reuse the EBS volumes, that are dynamically provisioned by the AWS EBS CSI driver, after destroying and recreating the EKS cluster?

**Comment by torredil** [comment]
Specifying a `Retain` reclaim policy in the `StorageClass` allows for manual reclamation of the resource. To reuse the previously dynamically provisioned EBS volume, you can create a new `PersistentVolume` with the same storage asset definition.

**Comment by kuppuswamy** [comment]
Could automatic reclamation of the previously dynamically provisioned EBS volumes after the recreation of EKS cluster be considered as a possible feature request? Or, is there any logic or behavior that strictly doesn’t allow this automatic reclamation to be part of the EBS CSI driver?

**Comment by ConnorJC3** [comment]
No. Indicating that a volume is available for reuse (by recreating a PV for it in your case) is something the user must do, because it conveys intent. Just because a volume looks like it happened to come from a previous cluster does not mean it is necessarily safe to reuse - it could contain important data or be in use by another cluster. We need the user to confirm these volumes are safe to use (by creating a corresponding PV for them).

The driver will only ever use a volume it is 100% confident it is entitled to use (it created it, it was specified for use via k8s by creating a PV, etc) because the alternative involves potentially overwriting user data.

**Comment by kuppuswamy** [comment]
Understood. And based on your comment, I created a Lambda, that uses AWS SDK to fetch the required dynamically provisioned EBS volumes, that are to be reused, and creates PersistentVolumes with claimRef using the tags present in the fetched EBS volumes.

**Comment by kuppuswamy** [comment]
> > Understood. And based on your comment, I created a Lambda, that uses AWS SDK to fetch the required dynamically provisioned EBS volumes, that are to be reused, and creates `PersistentVolumes` with `claimRef` using the tags present in the fetched EBS volumes.
> 
> Sounds a neat approach. Is there documentation to do that somewhere?

I have created a GitHub repository of this Lambda, that I mentioned in the answer. Please refer to it. Link: [https://github.com/kuppuswamy/eks-pv-restorer.git](https://github.com/kuppuswamy/eks-pv-restorer.git)
