### ISSUE TITLE
migration from a self managed AWS CSI Driver via helm to the AWS Managed EKS Addon

### ISSUE THREAD

**Issue by captainfalcon23** [kubernetes-sigs/aws-ebs-csi-driver#1502]
I have a question regarding migration from a self managed AWS CSI Driver via helm to the AWS Managed EKS Addon and I cannot find any info online regarding this scenario. I have done alot of googling and cannot find any documentation around this process. 

Is it as simple as uninstall the self managed version, and install the addon via the AWS console, and everything will just magically work? Is there any risk in this, or any lost functionality or anything else to be aware of? Will volumes get orphaned or any state get messed up?

/triage support

**Comment by torredil** [comment]
> Is it as simple as uninstall the self managed version, and install the addon via the AWS console, and everything will just magically work?

Yes, as simple as that.

> Is there any risk in this, or any lost functionality or anything else to be aware of? Will volumes get orphaned or any state get messed up?

During the transition from self-managed to EKS-managed there will be a small amount of down time in the sense that you will be unable to create, delete, or mount/unmount any volumes since the driver is unavailable. The good news is that volumes that have already been mounted will continue to work with no downtime.

**Comment by torredil** [comment]
/close

Feel free to re-open if you have any additional questions on this topic, thanks!
