### ISSUE TITLE
Not able to install on a non-eks cluster

### ISSUE THREAD

**Issue by rhythmbhiwani** [kubernetes-sigs/aws-ebs-csi-driver#1592]
I am using a self hosted kubernetes cluster on some cloud instance, and wanted to use storage classes with ebs, but it was not working as expected, then I landed on this repo and it seems like I need to install this before PV can be created in the cluster.

I tried installing it as guided in the docs using helm, but the pod was in `crashloopbackoff` state, and after checking the logs, it seems like it's not able to find the region, and after trying to find using the metadata api, that also fails because the server is not on aws.

I also tried modifying the values.yaml file, and also manually adding region in templates/controller.yaml file, but then the result it same.

Please help me in this, I'm first time doing this

/triage support

**Comment by rdpsin** [comment]
Hi, this is expected since EBS volumes can only be attached to EC2 instances (or AWS Outposts). When the driver starts, it needs to query IMDS to get instance information; otherwise, it won't be able to run. If you want to use EBS volumes, you need to have a clusters on AWS (either through self-managed installation or EKS).

**Comment by ConnorJC3** [comment]
/close

As @rdpsin mentioned, the EBS CSI Driver is specifically designed for EBS, and will only work where EBS does (i.e. on AWS).

The Kubernetes project maintains a list of CSI Drivers, one of them there may suit your needs: https://kubernetes-csi.github.io/docs/drivers.html
