### ISSUE TITLE
Is it safe to switch between add-on <-> Helm deployments?

### ISSUE THREAD

**Issue by makarov-roman** [kubernetes-sigs/aws-ebs-csi-driver#1616]
Hi, I support multiple clusters and some of them are using EKS addon and some helm, I want to unify this behavior. Can you advise if it safe to replace one with another? 

/triage support

**Comment by torredil** [comment]
Hi @makarov-roman thanks for reaching out. It is indeed safe to replace one deployment method with the other. Both versions of the EBS CSI Driver - the self-managed version via Helm, and the Amazon EKS managed version via add-on - are fully supported. 

That said, we typically recommend using the EKS managed add-on as it reduces the amount of work that you need to do in order to install, configure, and update the driver. All Amazon EKS add-ons include the latest security patches, bug fixes, and are validated by AWS to work with EKS. However, depending on your specific use case you might find the self-managed version to be more suitable.

Let me know if you run into any issues during your transition and I'll be happy to help.
