### ISSUE TITLE
csi-snapshotter Failed to watch 

### ISSUE THREAD

**Issue by doramar97** [kubernetes-sigs/aws-ebs-csi-driver#1662]
I'm using the aws-ebs-csi-driver installed on EKS 1.24. I receiving a lot of errors and cant perform a snapshot. I don't need to perform a snapshot because I have no volumes on my cluster, but my logs are flooded. 

`E0629 07:17:15.672926       1 reflector.go:140] k8s.io/client-go@v0.25.2/tools/cache/reflector.go:169: Failed to watch *v1.VolumeSnapshotContent: failed to list *v1.VolumeSnapshotContent: the server could not find the requested resource (get volumesnapshotcontents.snapshot.storage.k8s.io)`

The driver installed with Terraform, as an eks addon: 

```
resource "aws_eks_addon" "aws_ebs_csi_driver" {
  cluster_name      = local.cluster_name
  addon_name        = "aws-ebs-csi-driver"
  addon_version     = "v1.13.0-eksbuild.1"
  resolve_conflicts = "OVERWRITE"

  depends_on = [ module.eks ]

}
```

What can be the issue here ? 
Will be happy to provide more information if needed. 

/triage support

**Comment by doramar97** [comment]
@torredil Thanks for your answer, but i can see the value default is false in the[ values file](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/v1.20.0/charts/aws-ebs-csi-driver/values.yaml) of the helm chart. And i'm not sure how to override values through an aws eks addon, would you recommend  on using the helm chart directly ?

**Comment by torredil** [comment]
@doramar97 That is correct, if you install the EBS CSI Driver via Helm, `forceEnable` will be set to false by default. For the EKS add-on version of the driver, `forceEnable` defaults to true for backwards compatibility. 

> i'm not sure how to override values through an aws eks addon

Check this out: [Amazon EKS add-ons: Advanced configuration](https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/).

In summary, using the EKS add-ons advanced configuration feature you can specify this configuration directly through the Amazon EKS add-ons API or through the console, at your preference. Heres an example of how to set this value using either method:

- Console: `EKS -> Clusters -> <your_cluster> -> Add-on: aws-ebs-csi-driver -> Advanced configuration`

```
sidecars:
  snapshotter:
    forceEnable: false
```

- CLI:

```
$ cat config.yaml 
--------               
sidecars:
  snapshotter:
    forceEnable: false
--------

$ aws eks update-addon --cluster-name <CLUSTER_NAME> \
--addon-name aws-ebs-csi-driver --addon-version v1.20.0-eksbuild.1 \
--configuration-values 'file://config.yaml' \
--resolve-conflicts OVERWRITE
```

To confirm that the config worked, you can describe the controller pod and should see that the `csi-snapshotter` container is no longer part of it

> would you recommend on using the helm chart directly 

Both versions of the EBS CSI Driver - the self-managed version via Helm, and the Amazon EKS managed version via add-on - are fully supported.

That said, we typically recommend using the EKS managed add-on as it reduces the amount of work that you need to do in order to install, configure, and update the driver. All Amazon EKS add-ons include the latest security patches, bug fixes, and are validated by AWS to work with EKS. However, depending on your specific use case you might find the self-managed version to be more suitable.

**Comment by doramar97** [comment]
@torredil Changing the configuration from the console worked for me !
I didnt really found a way to edit values from an aws_eks_addon Terraform resource.
The issue is probably that the crd's are not installed, maybe installing them on my cluster could solve the problem as well. 
Thanks !

**Comment by torredil** [comment]
@doramar97 Happy to hear. Feel free to ping me or reach out anytime, we are here to help 👍

/close
