### ISSUE TITLE
failed to get disk format of disk /dev/nvme1n1: exit status 127

### ISSUE THREAD

**Issue by rusk0** [kubernetes-sigs/aws-ebs-csi-driver#1784]
/kind bug

**What happened?**
I had an old AWS EKS kubernetes cluster, running 1.21, so i decided to upgrade it.
While upgrading to 1.23 if not mistaken i was prompted that i need to install the AWS EBS CSI driver, so i did through the AWS Console --> Clusters --> Addons (latest version)

After installing the plugin however, a redis deployment, that requires a gp2 volume can't be created with the following error :

**kubectl describe pod redis-b9d65796c-psdkw**  

`  Warning  FailedMount             2s (x5 over 9s)  kubelet                  MountVolume.MountDevice failed for volume "pvc-aed078f4-658f-4656-90c0-44bb8b347e2a" : rpc error: code = Internal desc = could not format "/dev/nvme1n1" and mount it at "/var/lib/kubelet/plugins/kubernetes.io/csi/ebs.csi.aws.com/e252b2dda3ccd485b35aa3719d2930464320c09504b4a63d2d029e7e64d42c99/globalmount": failed to get disk format of disk /dev/nvme1n1: exit status 127`

**What you expected to happen?**
I expect that the volume will be mounted properly, as it is getting attached fine to the eks worker node and is properly formated as ext4.

**How to reproduce it (as minimally and precisely as possible)?**
Deploy a simple redis app in a kubernetes cluster, using gp2 storageclass as a volume provisioner and the ebs csi plugin and describe the redis pod, which should be stuck on ContainerCreate phase.

**Anything else we need to know?**:
I have set up IAM roles, policies and permissions as described in [the docs](https://docs.aws.amazon.com/eks/latest/userguide/csi-iam-role.html)
No volume encryption exists.
I have tried both the helm version and the AWS Console version just in case.
I assume it's maybe somehow related to the arm arch, as i have another envs with similar configurations, except the arch.
Any clues are greatly appreciated !

**Environment**
- Kubernetes version (use `kubectl version`):
1.23 / 1.24 / 1.25 / 1.26 - tried them all
EKS workers are A family, so they are arm64 arch

- Driver version:
v1.23.1-eksbuild.1

**Comment by AndrewSirenko** [comment]
Hi @rusk0, thank you for bringing this to our attention.

We investigated this issue and discovered that v1.23.0, v1.23.1, and v1.24.0 of the aws-ebs-csi-driver cannot be used with A1 instance types due to A1 instances not supporting AL2023 (which we upgraded our driver base image to for Linux in [v1.23.0](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG.md#urgent-upgrade-notes)).

**For now, please install v1.22.1 of the aws-ebs-csi-driver addon, instead of 'latest version'** while we resolve this issue.

**Comment by torredil** [comment]
A fix for this issue is available in driver version `1.24.1`+ (also back-ported to `1.23.2`) via the [a1CompatibilityDaemonSet](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/130cb817e6bb79b3b940573db580badc8b8b62c6/charts/aws-ebs-csi-driver/values.yaml#L417) parameter (disabled by default). Enabling this parameter will deploy an additional `DaemonSet` for the node service that specifically targets A1 instances using AL2 as the base image.

Users installing the driver as an EKS add-on can set this parameter via the EKS [advanced configuration](https://aws.amazon.com/blogs/containers/amazon-eks-add-ons-advanced-configuration/) feature:

```
{
  "a1CompatibilityDaemonSet": true
}
```

/close

**Comment by gitarns** [comment]
1.30 and still not fixed.
