### ISSUE TITLE
Snapshots of migrated Volumes

### ISSUE THREAD

**Issue by steveizzle** [kubernetes-sigs/aws-ebs-csi-driver#1795]
/kind bug

**What happened?**
After migration of an existing PVC from in-tree to out-of-tree some of the CSI features can not be used, like snapshots.

**What you expected to happen?**
For example taking snapshots should work.  

**How to reproduce it (as minimally and precisely as possible)?**

1. create volume with in-tree
2. check if it got migrated by checking the annotations
3. create VolumeSnapshots with the snapshot-controller
4. Created Snapshot says "Failed to set default snapshot class with error snapshotting non-CSI volumes is not supported"

**Anything else we need to know?**:

**Environment**
- Kubernetes version (use `kubectl version`): Server Version: version.Info{Major:"1", Minor:"28+", GitVersion:"v1.28.2-eks-f8587cb", GitCommit:"cd9e2116ea8721771e0f7be9150c4f3c4244815f", GitTreeState:"clean", BuildDate:"2023-09-18T22:11:02Z", GoVersion:"go1.20.8", Compiler:"gc", Platform:"linux/amd64"}
- Driver version: v1.24.0

**Comment by ConnorJC3** [comment]
/close

This is an intentional Kubernetes limitation, see https://github.com/kubernetes-csi/external-snapshotter/issues/489#issuecomment-813597826

Volumes that are handled via CSI Migration (i.e. volumes with a StorageClass that references the in-tree provisioner, rather than `ebs.csi.aws.com`) do not support some new CSI features such as snapshotting.

In order to utilize the full CSI feature set, you will need to create new volumes with a `StorageClass` that uses the CSI provisioner `ebs.csi.aws.com`.
