### ISSUE TITLE
Possible wrong tagged commit for `v1.25.0`

### ISSUE THREAD

**Issue by muscionig** [kubernetes-sigs/aws-ebs-csi-driver#1839]
/kind bug

**What happened?**
I believe the tag `v1.25.0` has been applied to the wrong commit, see this: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/479f6e8a89cba4558306240574d2e9fd789b1ca4/deploy/kubernetes/base/controller.yaml#L64

I went and deployed the new version, and I got stuck in a `crashlookbackoff` until I switched the image tags to `1.25.0`, as done in this commit: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/commit/2cc342fe699f2a2801f62fb930f20cad891feec2.

**Anything else we need to know?**:

Feel free to close this issue in case this is expected.

**Environment**
- Kubernetes version (use `kubectl version`): 1.27
- Driver version: 1.25.0

**Comment by AndrewSirenko** [comment]
Hi @muscionig, thank you for reaching out (and I'm glad you were able to figure out how to deploy the new version of our driver). 

We recommend users install the driver through the officially supported methods found in our [install.md documentation](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md) or [the EKS add-on documentation](https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html), so I will close this for now. 

However, you are correct that our version tagging is inconsistent with other open source software projects (due to a quirk of our release process). I have added a backlog item to alleviate this. 

Thanks again for sharing your experience, this type of feedback is very useful to us!

**Comment by ConnorJC3** [comment]
/close

Hi, thanks for the feedback:

This is, for the moment, expected. We use tags to indicate the version of the code that is built into a specific release's binary and container. The manifests cannot be updated at that time, because the images don't yet exist so users installing from the release branch would fail to install.

For the moment, please install using the release branches, [example from our installation docs](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/docs/install.md#kustomize).

We'll take this as a suggestion for future improvement. However, changing this would require a significant rework of the way we currently perform releases, so I wouldn't expect it changed in the near future.
