### ISSUE TITLE
external-provisioner and external-attacher containers are frequently and randomly restarting

### ISSUE THREAD

**Issue by IulianApostol** [kubernetes-sigs/aws-ebs-csi-driver#1944]
/kind bug

In my ebs-controller, my provisioner and attacher containers, work fine for while, and then suddenly it logs with Lost connection to unix socket and exiting.  Then the pod gets restarted. This happens randomly, I have yet to find a pattern of processes that would provoke this, it happens randomly and restarts the pod daily about 10 times. 
 
 Has anyone else experienced this?

**Environment**
- Kubernetes version (use `kubectl version`): 1.25.0
- Driver version: 1.25.0

**Comment by torredil** [comment]
Hi @IulianApostol thank you for reporting this. 

This is likely related to https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/1875, which was fixed in driver version `1.26.1` - for more details see the [CHANGELOG](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG.md#v1261). Please upgrade to the latest version of the driver and let us know if the issue persists.

**Comment by IulianApostol** [comment]
Thank you @torredil, I had a hunch about updating the driver and now you confirmed it!  
I updated the version,  will update the issue tomorrow:)

**Comment by IulianApostol** [comment]
I confirm this issue was fixed when upgrading the driver, many thanks :)
