### ISSUE TITLE
Node Unit Test Failing on Mac

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#206]
/kind bug

**What happened?**
When I run `make test` on my mac machine, two node_test.go unit test are failing with errors:
```
--- FAIL: TestNodeStageVolume (0.00s)
    --- FAIL: TestNodeStageVolume/success_normal (0.00s)
        node_test.go:211: Expected mount points {[{Device:/dev/fake Path:/test/path Type:ext4 Opts:[defaults] Freq:0 Pass:0}]}, got {[{Device:/dev/fake Path:/test/path Type:ext4 Opt
s:[] Freq:0 Pass:0}]}
    --- FAIL: TestNodeStageVolume/success_mount_options_fsType_ext3 (0.00s)
        node_test.go:211: Expected mount points {[{Device:/dev/fake Path:/test/path Type:ext3 Opts:[defaults] Freq:0 Pass:0}]}, got {[{Device:/dev/fake Path:/test/path Type:ext3 Opt
s:[] Freq:0 Pass:0}]}
```

This is not happening on Prow unit test

**What you expected to happen?**
Unit test pass on mac

**How to reproduce it (as minimally and precisely as possible)?**
Run `make test` on mac.

/cc @sreis

**Comment by sreis** [comment]
@leakingtapan I had a quick look and it's because the [formatAndMount](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount_linux.go#L437) will only append the options when running on Linux. You're running on Mac so it just uses goes directly to the [Mount call](https://github.com/kubernetes/kubernetes/blob/master/pkg/util/mount/mount_unsupported.go#L85-L87) of the FakeMounter we setup for the tests.

**Comment by leakingtapan** [comment]
We should consider options proposed [here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/233). And potential expand this to support to test nvme volume support which going to be added recently
