### ISSUE TITLE
Enabling volumeMode: filesystem for multi attach ebs volumes in ebs-csi-driver.

### ISSUE THREAD

**Issue by shalevbell** [kubernetes-sigs/aws-ebs-csi-driver#2176]
**Is your feature request related to a problem?/Why is this needed**
I am using ebs-csi-driver with postgresql pods used in CI tests, I have an issue of the cluster moving the pods between nodes sometimes in the middle of tests and having about 3 minutes of downtime until the ebs is removed from the previous node and moved to the new one and in that time having many test failures.

/feature

**Describe the solution you'd like in detail**
I want to move to using multi-attach ebs volumes with the ebs-driver so now the ebs will be attached to the new node without having to wait for the disconnect from the first node.
I need the mount to be a filesystem so I can save all the DB data inside for data persistency.
Currently the volumeMode can only be set to block.

**Describe alternatives you've considered**
I tried to use an init container to create the file system using mkfs but it couldnt get it to work right and seems like a workaround to an issue that could be solved with this option being enabled. What is the thought behind the option only being block is there a specific restriction?

**Additional context**
Deploying postgresql pod on eks cluster in eu-central-1 for CI tests and want fast data persistency even when pod is moved to other node inside cluster during tests.

**Comment by kimxogus** [comment]
@ConnorJC3 I fully understand why it's intended, but we need to add SYS_ADMIN capability to mount the volume. it violates our psa policy. What about mounting them in readonly mode?

**Comment by ConnorJC3** [comment]
Hi, we evaluated offering read-only support for filesystem volumes at the time of the feature's design/development, but decided not to do so because:

1. Mounting read-only is not sufficient to prevent writing to the volume (and thus, potential data loss in a multi-attach scenario). For example, `ext4` will perform writes to the disk due to the journal even when mounted read-only.

2. Kubernetes and CSI do not distinguish mounting versus creating volumes, making it difficult/impossible to allow mounting but not creating such volumes.\

3. Although it may be possible to use conventional filesystems safely in a multi-attach environment, this is not a supported usecase and requires significant additional care (for example, the issue above about potential writes even in read only mode). The EBS CSI Driver takes on the responsibility of creating, attaching, and making available to pods multi-attach volumes as a block device, but we will not be taking on the responsibility of interacting with filesystems on such volumes.
