### ISSUE TITLE
Implement Snapshot support

### ISSUE THREAD

**Issue by leakingtapan** [kubernetes-sigs/aws-ebs-csi-driver#25]
Driver implementation should support following operations:
 - [x] CreateSnapshot
 - [x] DeleteSnapshot
 - [ ] ListSnapshots
 - [x] CreateVolume from snapshot

References:
* https://kubernetes.io/docs/concepts/storage/volume-snapshots/
* https://kubernetes.io/docs/concepts/storage/volume-snapshot-classes/
* https://kubernetes-csi.github.io/docs/Implement-Snapshot-Feature.html

**Comment by bertinatto** [comment]
CC @tsmetana

**Comment by leakingtapan** [comment]
Punt the feature to beta release

**Comment by tsmetana** [comment]
First version (does not implement snapshot listing yet): https://github.com/tsmetana/aws-ebs-csi-driver/tree/snapshots-updated

It's based on PR#122 (CSI-1.0) so I will wait with my PR.

**Comment by bertinatto** [comment]
@tsmetana: we just merged my PR into `next` branch. If you want to proceed with you PR you can point it against `next` as well.

**Comment by leakingtapan** [comment]
/assign @dkoshkin
Dimitri will help debugging issues related to snapshot

**Comment by tsmetana** [comment]
OK. I'm not sure which is the right place to discuss this... What is happening with the snapshots: in the waitForSnapshotCreate there is an truncated exponential backoff with a condition function that basically polls for the snapshot unitl it's "completed" or an error occurs. The polling loop uses ec2.DescribeSnapshotsWithContext(ctx, ...). After few iterations this call fails with GRPC error ("DeadlineExceeded" iirc). 

Looks like the issue is that the CreateSnapshot CSI call should be blocking (by specification) but the GRPC connection times out prematurely -- it's unknown how long time a snapshot creation might take. The controllers (external snapshotter in our case) should be able to handle that -- for example external attacher distinguishes the fatal and transient errors like this: https://github.com/kubernetes-csi/external-attacher/blob/master/pkg/connection/connection.go#L256

I guess similar mechanism needs to be implemented also in the external snapshotter, otherwise this patch will not work...

**Comment by tsmetana** [comment]
The issues I mentioned in the previous comment were worked around in the patch that's been recently merged.

**Comment by leakingtapan** [comment]
@tsmetana just to confirm that is `ListSnapshot` is used by k8s yet, so it is not implemented?

**Comment by tsmetana** [comment]
No, ListSnapshot is not implemented yet. I'll add it to my TODO.

**Comment by leakingtapan** [comment]
@tsmetana I created a follow up issue for the left task: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/233

I am going to close this one since the major tasks are done.

/close
