### ISSUE TITLE
Run kubernetes e2e tests without migration

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/aws-ebs-csi-driver#406]
E2E tests for CSI migration are added in #294. We need the same e2e tests also with plain CSI driver, without migration. 

In other words, install the driver and run upstream e2e tests with the CSI driver (with the driver in StorageClass, no migration), as described in https://github.com/kubernetes/kubernetes/blob/master/test/e2e/storage/external/README.md.

Since most of the work (cluster & driver installation) is already done, it could be a simple ginkgo command in a new prow job.

/feature

**Comment by leakingtapan** [comment]
Another additional work is the current [testing script ](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/hack/run-e2e-test) is not that configurable for tuning feature gates (hard coded to enabled migration). I have already written a [new](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/tester/single-az-config.yaml) framework (which is more configurable) for e2e testing, I need make changes to create 1.16+ cluster (due to kops is not yet officially released to 1.16+ cluster)

The other idea is we can combine the upstream e2e testing suites with the existing e2e suites instead of creating new make target.

**Comment by leakingtapan** [comment]
> due to kops is not yet officially released to 1.16+ cluster
I just switched to use kops 1.16 alpha: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/409

**Comment by AndyXiangLi** [comment]
We already add external e2e test in [PR](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/726)
This can be closed when upstream test-infra update our CI https://github.com/kubernetes/test-infra/pull/20747

**Comment by ayberk** [comment]
OK let me close this one. I'll get that merged today.

/close
