### ISSUE TITLE
Max number of volumes calculation is incorrect

### ISSUE THREAD

**Issue by tenitski** [kubernetes-sigs/aws-ebs-csi-driver#427]
/kind bug

**What happened?**
Unable to start a pod which uses a volume:

> Warning  FailedAttachVolume  22m (x3 over 70m)    attachdetach-controller                                   AttachVolume.Attach failed for volume "pvc-?????" : timed out waiting for the condition
  Warning  FailedMount         119s (x41 over 92m)  kubelet, ip-???????.ap-southeast-2.compute.internal  Unable to mount volumes for pod "mysql-0_example(?????)": timeout expired waiting for volumes to attach or mount for pod "example"/"mysql-0". list of unmounted volumes=[mysql-data]. list of unattached volumes=[mysql-data default-token-????]
0

There are over 20 volumes mounted on the instance, no more can be mounted.

**What you expected to happen?**

When mounting volumes on nodes which use multiple ENIs the max limit is calculated incorrectly as ENIs use some of the resources (it is very well described in this ticket https://github.com/kubernetes/kubernetes/issues/80967).

Driver should check how many ENIs are in use and decrease the number of volumes.
Other option is allow external param to limit number of volumes by admin.

**Environment**
- Kubernetes version (use `kubectl version`):
> Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.8-eks-b7174d", GitCommit:"b7174db5ee0e30c94a0b9899c20ac980c0850fc8", GitTreeState:"clean", BuildDate:"2019-10-18T17:56:01Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

- Driver version:
I'm not sure what specific driver version it is. The cluster was created using `terraform-aws-eks v6.0.2` module (https://github.com/terraform-aws-modules/terraform-aws-eks?ref=v6.0.2)

**Comment by leakingtapan** [comment]
@tenitski Thx for creating the issue here. As I mentioned in the other [thread](https://github.com/kubernetes/kubernetes/issues/80967#issuecomment-521302485) 

> Agree with @justinsb that, to make it working correctly, the challenge comes from storage driver need to be aware of the CNI attachment and vice versa.

We need a way to let CNI plugin and CSI driver to share this attach limit so that both side could work correctly. And the current CSI attach limit feature doesn't address this issue at all.

**Comment by gnufied** [comment]
I do not think we will have a design that will allow flexibility we are looking for in calculating CNI and impact of other network interfaces (at least in short/medium term). 

We should fix - https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/347

**Comment by otterley** [comment]
I disagree with the approach suggested in #347 - I don't believe we should burden our customers with the responsibility of determining what the correct value should be, especially when we can calculate that for them, and because the values could be raised in the future.   

It could also customers into a false sense of correctness and reliability. If they set the value too high because of how many ENIs are attached when the node is young, another ENI attachment that occurs unbeknownst to the customer could make the configured limit incorrect, and lead to more errors in scheduling pods.  We should strive for the most reliable solution possible.

**Comment by excieve** [comment]
I've just bumped into this issue on an EKS 1.14.9 cluster with a VPC CNI plugin installed. After reading the (closed) https://github.com/kubernetes/kubernetes/issues/80967 issue, I understand that dynamic limit is now GA with 1.17, but does EBS CSI actually report a correct limit for it?

More general question: is there a way to reliably use the EBS CSI at all? Right now volumes are just stuck at "attaching" once over the "real" limit.

**Comment by ashaker-cig** [comment]
This issue forces cluster admins to set a static low value for volume-attach-limit to avoid running into attachment issues on nodes using AWS VPC CNI. Which leads to premature Node scaling-out and inefficient use of resources. 
It would be great if the driver became aware of the current attachments (ENI & EBS) on its EC2 instance and calculate  the max number accordingly.

**Comment by ashaker-cig** [comment]
I think I just noticed fixing and merging [#1075] might address this issue, on nodes where DescribeInstances is granted in their IAM roles. Right?
