### ISSUE TITLE
CSI support attach a volume to multiple instances with amazon EBS Multi-Attach

### ISSUE THREAD

**Issue by Missshao** [kubernetes-sigs/aws-ebs-csi-driver#449]
**Describe the solution you'd like in detail**
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volumes-multi.html

**Comment by varunkumar** [comment]
Is there any WIP on this?

**Comment by leakingtapan** [comment]
Hey, there is no progress on this feature yet as we still need the design for this

**Comment by gzur** [comment]
> Hey, there is no progress on this feature yet as we still need the design for this

Are there any design discussions happening somewhere else?

**Comment by rubenstolk** [comment]
Would love to understand if there will be any progress on this?

**Comment by ayberk** [comment]
/lifecycle frozen

cc @AndyXiangLi

**Comment by coder0028** [comment]
Is there any progress? There is an open issue on stackoverflow [https://stackoverflow.com/a/67210073/7755174](https://stackoverflow.com/a/67210073/7755174)

**Comment by AndyXiangLi** [comment]
@coder0028 We haven't start on this feature but any help are welcome!

**Comment by yrsurya** [comment]
Any update on this? pls let us know

**Comment by andreazorzetto** [comment]
Hi everyone, I'd like to learn about any progress on this too

**Comment by jsravn** [comment]
Multi-attached EBSs have several limitations. I'm wondering how people are expecting to actually use this? It won't be as simple as attaching a PVC to multiple pods:

> Standard file systems, such as XFS and EXT4, are not designed to be accessed simultaneously by multiple servers, such as EC2 instances. Using Multi-Attach with a standard file system can result in data corruption or loss, so this is not safe for production workloads. You can use a clustered file system to ensure data resiliency and reliability for production workloads.

> Multi-Attach enabled volumes do not support I/O fencing. I/O fencing protocols control write access in a shared storage environment to maintain data consistency. Your applications must provide write ordering for the attached instances to maintain data consistency.

From https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-volumes-multi.html.

Seems like it would only be useful for specialized purposes - if people tried using multi-attached EBSs as shared PVCs with typical filesystems they are going to run into a world of pain.

**Comment by jbg** [comment]
Those caveats are common to multiple writers on any shared block storage aren't they?

Our application is to write once, detach the writer and then attach read only to many. So a clustered FS is not needed.

**Comment by ksliu58** [comment]
+1 to @jsravn above. 

What use cases is everyone trying to solve? How you plan to use it?

**Comment by jsravn** [comment]
> Those caveats are common to multiple writers on any shared block storage aren't they?
> 
> Our application is to write once, detach the writer and then attach read only to many. So a clustered FS is not needed.

Even ext4 writes back to the journal on readonly mounts. So you're playing with fire and risking your data in a major way. Not a good idea.

> If we had multi-attach EBS, we would have no need for the affinity assistant (our pod templates would restrict it to running in the same zone, of course) and this would improve our build times and even out our EC2 utilisation.

No, multi-attach doesn't give you this. It's shared block storage, not a clustered file system that supports shared writes. Maybe you want K8s to manage/setup something like GFS for you?

**Comment by jbg** [comment]
> Even ext4 writes back to the journal on readonly mounts. So you're playing with fire and risking your data in a major way. Not a good idea.

"playing with fire and risking your data in a major way" is FUD. It's *completely fine* to attach multiple readers (with no writers) in a way that is entirely safe:

* Ensure the filesystem was unmounted cleanly
* Make the underlying block device read-only (not strictly needed, but helps avoid mistakes)
* Mount with `ro,noload` (`noload` is safe because there is no journal to replay — the filesystem was unmounted cleanly)

If you can't ensure these constraints then don't do it. But it's perfectly safe if done properly.

**Comment by jsravn** [comment]
That's fine, I think you're free to do what you want. I personally wouldn't risk disabling journalling, even read-only, in the general case (due to nodes crashing/EBS's hanging/etc.), but it might work for your particular niche use case as long as data isn't transactional. So it sounds like you're saying just give us shared block storage, let us do what we want on it. I think that's a fair enough request.

I do feel the majority of people up voting this think it gives them a lot more than just shared block storage. If they're looking for multiple writers as @KeenanLawrence seems to, then K8s needs to manage some sort of shared disk FS on top of the multi-attach storage, so we probably need to add support for that elsewhere.

**Comment by jbg** [comment]
> I personally wouldn't risk disabling journalling, even read-only, in the general case (due to nodes crashing/EBS's hanging/etc.)

There are no writes to the journal on a read-only mount even if nodes crash, the block storage hangs, or anything else. The only writes that will ever occur on a read-only mount are on startup to replay the journal, *if and only if the filesystem was not unmounted cleanly*.

With extfs there are enormous risks of having multiple readers *if any writer exists*, but (assuming the last read/write mount was unmounted cleanly) there are zero risks of multiple readers *if no writer exists*. It's not that niche a case, honestly.

I would think that this driver should focus on the block storage part? As far as I understand it, `fsType` can be anything supported by the node, so quite a few Linux clustered filesystems should immediately be possible if this driver can supply the multi-attached block storage.

**Comment by jsravn** [comment]
Sorry, deleted my comment because I felt I was going way off topic.

I agree the driver should just focus on the block storage part.

AFAIK there is no "fsType" that would support it right now - they usually all require supporting infrastructure like Redhat DLM for GFS. There is also the question of I/O fencing which multi-attach doesn't support. It's likely more work will have to be done on the K8s storage side to provide the functionality people are expecting.

I'd think right now this would just be used in block storage mode and users have to manage it themselves by setting up the infra needed. Or carefully manage the mount lifecycle like you suggest.

**Comment by jeevanragula** [comment]
Any updates on this issue? 
Are there plans to add this feature of supporting multiAttach in the CSI driver?
I see there is a PR raised but in a closed state now.
https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/1177
If needed, I can take up and raise a PR.

**Comment by daecabhir** [comment]
Is there a particular reason why, for pods requiring a standard filesystem, that EFS / NFS is not a viable solution to the problem. It seems to be way less complicated, have far fewer pre-conditions (e.g. pre-building volumes, ensuring clean unmouts, etc.) and is fully supported by EKS, EKS Fargate and standalone Kube. Multi-attach is provided largely to meet very specific use cases where software needs concurrent access to manage a block device / filesystem, whereas EFS is really intended to address the broader generic shared filesystem functionality.

**Comment by sebastianlzy** [comment]
> Is there a particular reason why, for pods requiring a standard filesystem, that EFS / NFS is not a viable solution to the problem. It seems to be way less complicated, have far fewer pre-conditions (e.g. pre-building volumes, ensuring clean unmouts, etc.) and is fully supported by EKS, EKS Fargate and standalone Kube. Multi-attach is provided largely to meet very specific use cases where software needs concurrent access to manage a block device / filesystem, whereas EFS is really intended to address the broader generic shared filesystem functionality.

One common reason I had in using EBS multi-attach instead of EFS is cost (On a cost perspective only, EFS is ~2-3x more expensive than EBS - io2).  In addition, I will also like to perform a lift and shift migration to EKS from VM, replicating what the workload have been using VMs (multiple EC2 to 1 EBS volume)

**Comment by bruno-chavez** [comment]
Another use case for this feature is enabling persistent volumes for Windows worloads, FSx for Windows File Server is not always a choice since you need an Active Directory Domain to even deploy a FSx file system

**Comment by tom10271** [comment]
https://docs.aws.amazon.com/ebs/latest/userguide/ebs-volumes-multi.html#considerations

Latest io1 EBS supports I/O Fencing


> Multi-Attach enabled io2 volumes support I/O fencing. I/O fencing protocols control write access in a shared storage environment to maintain data consistency. Your applications must provide write ordering for the attached instances to maintain data consistency. For more information, see [Use NVMe reservations with Multi-Attach enabled Amazon EBS volumes](https://docs.aws.amazon.com/ebs/latest/userguide/nvme-reservations.html).
