### ISSUE TITLE
[DOCS] Elaborate on migration instructions

### ISSUE THREAD

**Issue by iainbryson** [kubernetes-sigs/aws-ebs-csi-driver#480]
Currently, the docs say this:

> To turn on the migration, set CSIMigration and CSIMigrationAWS feature gates to true for kube-controller-manager and kubelet.

It would be great to link to (or include inline) an example of this.  i.e. you start with a (presumably EKS) cluster with `StorageClass` with `provisioner: kubernetes.io/aws-ebs`, and you move to the CSI.  Apart from installing the CSI driver, what do you need to do?  Is just `apply`ing `provisioner: kubernetes.io/aws-ebs` on the storage class sufficient? Will it erase the volume? How exactly does one enable the feature gates (i.e. command line examples)?

/triage support

**Comment by leakingtapan** [comment]
Some the of questions are general CSI migration question that might covered in overall csi migration. Have you checked out this blog post: https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-csi-migration-beta/

**Comment by leakingtapan** [comment]
To answer ur questions:

> what do you need to do? Is just applying provisioner: kubernetes.io/aws-ebs on the storage class sufficient? 

Yes. The storage class with `provisioner: kubernetes.io/aws-ebs` should just work. And CSI migration aims at no frontend facing change. 

> Will it erase the volume? 

It will not. CSI driver will start in charge of the volume lifecycle management. and in-tree driver will stay down.

> How exactly does one enable the feature gates (i.e. command line examples)?

Just like how you enable other alpha feature flags. Depends on your cluster provisioning solution. [Here](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/hack/feature-gates.yaml#L7) is one example if you are using kops.

**Comment by cablespaghetti** [comment]
I've just been looking at this as precursor for switching to Bottlerocket (which doesn't have in-tree driver support) for our EKS clusters. We of course can't enable alpha feature flags in our EKS clusters.

The details are a bit thin on the ground but this blog post helped a lot: https://medium.com/faun/amazon-eks-upgrade-journey-from-1-16-to-1-17-cb9e88191165

This explains that the CSIMigrationAWS has not been enabled yet in EKS 1.17 and so we have to wait to migrate existing volumes. This is a shame because it basically rules out CSI and Bottlerocket for us. It sounds like we'll have to wait for a future revision of EKS 1.17 to get this.

Official AWS docs I've now found here: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.17

**Comment by mhausenblas** [comment]
Thanks for bringing this to my attention @cablespaghetti and I'm looking into it. From what I so far understand it seems to be an UX/DX issue combined with some missing bits. Let's see what we can do about this here.

**Comment by cablespaghetti** [comment]
@mhausenblas Am I correct in thinking that this hasn't yet progressed for EKS v1.18? I can't find any mention of `CSIMigrationAWS` being enabled. Thanks!

**Comment by mhausenblas** [comment]
> Am I correct in thinking that this hasn't yet progressed for EKS v1.18?

Not sure, hailing @jlbutler who might know better.

**Comment by ayberk** [comment]
@cablespaghetti I can confirm it's not enabled for 1.18. We'll definitely include it in the notes when we do.

**Comment by arohter** [comment]
EKS 1.20.4 is now out ... we don't see `CSIMigrationAWS` being enabled yet ...  any status update?

**Comment by wongma7** [comment]
@arohter it's not planned to be turned on by default in kubernetes until 1.22 and EKS doesn't intend to turn it on before that

Details on criteria for turning it on by default are here:
https://docs.google.com/document/d/1j6uF9sOoGCQ9nNFVrdvCWyn77o9k3-758qsEj2K3BAY/edit#heading=h.5jcp7r6168vr

**Comment by wongma7** [comment]
Some things that NEED to be documented/fixed somewhere BEFORE 1.22 release:

- The requirement to set --k8s-tag-cluster-id=$SAME_CLUSTER_ID_AS_kube-controller-manager on ebs-csi-controller container so that CSI-provisioned volumes get the same KubernetesCluster tag as in-tree-provisioned volumes. Especially if you rely on a tag-based IAM policy to control AttachVolume/ModifyVolume/CreateVolume/*Volume and other such operations. Only the user/distro(kops) knows the cluster name so it has to be set by them.
- The requirement to set --extra-create-metadata=true on external-provisioner container so that CSI-provisioned volumes get tagged the same PVC name/PVC namespace/PV name tags as in-tree-provisioned volumes. We can set this on user/distro behalf
