### ISSUE TITLE
Migration tests are constantly failing

### ISSUE THREAD

**Issue by jsafrane** [kubernetes-sigs/aws-ebs-csi-driver#560]
/kind bug

**What happened?**
https://testgrid.k8s.io/sig-aws-ebs-csi-driver#migration-test-latest is completely red.

From its logs:

```
/home/prow/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/tests/e2e-migration /home/prow/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver
go: k8s.io/kubernetes@v1.16.1 requires
	vbom.ml/util@v0.0.0-20160121211510-db5cfe13f5cc: unrecognized import path "vbom.ml/util": https fetch: Get "https://vbom.ml/util?go-get=1": dial tcp: lookup vbom.ml on 10.63.240.10:53: no such host
./hack/run-e2e-test: line 115: /home/prow/go/src/github.com/kubernetes-sigs/aws-ebs-csi-driver/bin/ginkgo: No such file or directory

```

I did not dig deep into this, just few observations:

1. Kubernetes 1.16 is really old
2. I would assume that after #555 no remote module fetch is necessary.

**Comment by wongma7** [comment]
yeah the migration test has its own go.mod, I guess to isolate it from the kubernetes libs of the driver itself so we can test a newer version without updating libs of driver: https://github.com/kubernetes-sigs/aws-ebs-csi-driver/tree/master/tests/e2e-migration. So need to repeat the same vbox.ml fix to stop trying to pull from there
/assign

**Comment by wongma7** [comment]
isolating the go.mod is probably not needed anymore,since the lib version being used by the driver is in fact newer and definitely contains the migration tests already

**Comment by wongma7** [comment]
They are now running but there are still some failures. In this one all the tests passed but it still reported failure for some reason... https://prow.k8s.io/view/gcs/kubernetes-jenkins/logs/ci-aws-ebs-csi-driver-migration-test-latest/1306841052396654592

**Comment by wongma7** [comment]
They are failing now because, based on my primitive method of checking, calls are still going to the in-tree driver instead of csi despite migration being enabled. Not sure why, I think anyway we should flip the 'MigrationComplete' flag


Port forwarding is not yet ready
Forwarding from 127.0.0.1:10252 -> 10252
Forwarding from [::1]:10252 -> 10252
Handling connection for 10252
Port forwarding is succeeded
Handling connection for 10252
Handling connection for 10252
volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="kubernetes.io/aws-ebs",le="0.1"} 0
volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="kubernetes.io/aws-ebs",le="0.25"} 0
volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="kubernetes.io/aws-ebs",le="0.5"} 0
volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="kubernetes.io/aws-ebs",le="1"} 0
volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="kubernetes.io/aws-ebs",le="2.5"} 0
volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="kubernetes.io/aws-ebs",le="5"} 0
volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="kubernetes.io/aws-ebs",le="10"} 46
volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="kubernetes.io/aws-ebs",le="15"} 46
volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="kubernetes.io/aws-ebs",le="25"} 46
volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="kubernetes.io/aws-ebs",le="50"} 46
volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="kubernetes.io/aws-ebs",le="120"} 46
volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="kubernetes.io/aws-ebs",le="300"} 46
volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="kubernetes.io/aws-ebs",le="600"} 46
volume_operation_total_seconds_bucket{operation_name="provision",plugin_name="kubernetes.io/aws-ebs",le="+Inf"} 46
TEST_PASS: 0 CSI_CALLED: 1 INTREE_CALLED: 0

**Comment by wongma7** [comment]
Now tests are using 1.18. 

Now only inline tests are failing.

Fix is here:
https://github.com/kubernetes/kubernetes/pull/96821

**Comment by ayberk** [comment]
/remove-lifecycle stale

New grid: https://testgrid.k8s.io/provider-aws-ebs-csi-driver#migration-test-latest

**Comment by ayberk** [comment]
We're green after the latest fix.

/close
