### ISSUE TITLE
`tolerationSeconds` for tolerations for controller

### ISSUE THREAD

**Issue by zerkms** [kubernetes-sigs/aws-ebs-csi-driver#588]
**Is your feature request related to a problem?/Why is this needed**
At the moment `tolerations` for the controller deployment https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/aws-ebs-csi-driver/templates/controller.yaml looks like this:

```yaml
      tolerations:
        - operator: Exists
```

which effectively allows it run everywhere. Which is fine. The problem is that with this toleration kubernetes won't reschedule the controller if a node where it runs suddenly becomes unavailable.

See https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/

> Kubernetes automatically adds a toleration for node.kubernetes.io/not-ready and node.kubernetes.io/unreachable with tolerationSeconds=300, **unless you, or a controller, set those tolerations explicitly.**

(highlight is mine)

So, you run it with default replica count 2, then you get unlucky and both nodes where those replicas run die. Now you end up having no ebs controller whatsoever and it won't fix without manual intervention.

/feature

**Describe the solution you'd like in detail**
I think the default `tolerationSeconds: 300` (configurable) should be added as well.

**Describe alternatives you've considered**
There is no, it's how kubernetes works.

**Additional context**

**Comment by ayberk** [comment]
This sounds reasonable to me.

/lifecycle frozen
/good-first-issue

**Comment by imbohyun1** [comment]
Observed the managed node group update with 'Pod Eviction Failure'. While upgrading managed node group with launch template version up, the node is tainted and all the pods should be evicted. But the node running on 'ebs-csi-controller' pod is not tainted fully because the 'ebs-csi-contoller' has a toleration. kube-scheduler keeps scheduling 'ebs-csi-controller' pod to the node which should be drained, and it prevents pods eviction until it hits max retries.
