### ISSUE TITLE
Driver image v0.8.1 missing from registry

### ISSUE THREAD

**Issue by Elassyo** [kubernetes-sigs/aws-ebs-csi-driver#685]
/kind bug

**What happened?**
I cannot deploy the driver because the driver image is missing from the container registries and cannot be pulled.
Trying to pull the image with docker result in a manifest not found error.

**What you expected to happen?**
The image should be present on the registry.

**How to reproduce it (as minimally and precisely as possible)?**
`kubectl apply -k "github.com/kubernetes-sigs/aws-ebs-csi-driver/deploy/kubernetes/overlays/stable/?ref=release-0.8"`
or
`docker pull k8s.gcr.io/provider-aws/aws-ebs-csi-driver:v0.8.1`
or
`docker pull amazon/aws-ebs-csi-driver:v0.8.1`

**Environment**
- Kubernetes version (use `kubectl version`): v1.18.9
- Driver version: v0.8.1

**Comment by wongma7** [comment]
https://github.com/kubernetes/k8s.io/pull/1509 just merged, it seems available now.

I'm sorry about this happening twice in a row, with the new release process there is a large window between when I update the yamls to refer to the new tags and when the tag actually gets pushed.

As I commented in https://github.com/kubernetes-sigs/aws-ebs-csi-driver/issues/646#issuecomment-756406782, I think the fix is to change our release process to update the yamls in a post-release update

**Comment by wongma7** [comment]
For docker hub, only the amazonlinux variant v0.8.1-amazonlinux is going to be available. I  will work on documenting this or getting permission to push the debian variant

**Comment by wongma7** [comment]
Regarding my last comment, here is a PR to ensure docker hub gets the debian base image (vx.x.x) and not just the amazonlinux one (vx.x.x-amazonlinux) https://github.com/kubernetes-sigs/aws-ebs-csi-driver/pull/686

**Comment by Elassyo** [comment]
Ok I can pull the image now, thank you!
