### ISSUE TITLE
There is no way to override the namespace of driver service accounts and deployments, statefulsets and daemonset in Charts

### ISSUE THREAD

**Issue by pjajootibco** [kubernetes-sigs/aws-ebs-csi-driver#829]
There is no way to override the namespace of driver service accounts and deployments, stateful sets, and daemonset in Charts

Can you please parameterize the namespace part for the applicable resources; so that we can choose to deploy them in the resources we desire.

**Comment by wongma7** [comment]
can you share the helm install command you are using? It should respect the namespace argument and deploy resources in that ns.

**Comment by tirumerla** [comment]
Hi @wongma7 - I'm having the same issue as i'm packaging multiple charts as subcharts ( csi sriver, cluster autoscaler, jupyterhub ). In this i would want csi driver, cluster autoscaler to be in it's own namespace ( preferably `kube-system`) and jupyterhub in it's own namespace ( eg. `jupyterhub`) When i do `helm install .... -n jupyterhub` both cluster autoscaler and ebs-csi driver are getting deployed in `jupyterhub` namespace. I tweaked multiple subcharts before by changing `Namespace: {{ .Release.Name }}` to `Namespace: {{ .Values.Namespace }}` that way we have flexibility giving different namespaces. I was wondering if i could do the same here. I gave it a try and looks like i'm able to replace service account, secrets etc. since they have `{{ .Release.Name }}` but not the pods itself. Do you have any other suggestions on how i can tweak this?

**Comment by pjajootibco** [comment]
> can you share the helm install command you are using? It should respect the namespace argument and deploy resources in that ns.

I tried the helm command from the documentation and I can see that it's deploying the resources in the namespace provided in the command. I think I had messed up earlier. Sorry for the trouble.

**Comment by wongma7** [comment]
no worries @pjajootibco !

@tirumerla do you mind creating a new issue? Could you link me to examples of other charts that let you override with .VAlues.Namespace? We have definitely struggled a little bit with helm installation best practices, so maybe we should add  support for .VAlues.Namespace override to be consistent with these other charts?
