### ISSUE TITLE
EBS and EFS storage controller node port conflict

### ISSUE THREAD

**Issue by fitchtech** [kubernetes-sigs/aws-ebs-csi-driver#868]
I cannot deploy both the aws-ebs-csi-driver and aws-efs-csi-driver to the same EKS 1.19 cluster. I get an error that no ports are available. If I deploy the EFS controller I cannot deploy the EBS controller and vice versa, can only deploy one of the other. Deploying EBS CSI v1 and EFS CSI v1.2 via the helm charts.

**Comment by wongma7** [comment]
yes, sorry about this, it should be fixed on the EFS side with helm chart 1.2.4: https://github.com/kubernetes-sigs/aws-efs-csi-driver/pull/439

Appreciate the report, it reminded me to get it merged.

IF problem persists, please create an issue in efs repo, efs is theone at fault!

In the long term, we don't want to require hostNetwork at all, of course besides the potential for port conflicts, it has security implications . We default to it for now because the driver currently needs access to instance metadata which is often blocked for pods but not on the host.
