### ISSUE TITLE
EBS CSI Driver helm charts are missing namespace information

### ISSUE THREAD

**Issue by tsunny** [kubernetes-sigs/aws-ebs-csi-driver#950]
/kind bug

**What happened?**
The helm charts do not have `namespace: {{ .Release.Namespace }}` field. This causes the template to not have namespace when with `helm template --namespace kube-system`

**What you expected to happen?**
Expected the namespace to be included in the generated manifests using helm

**How to reproduce it (as minimally and precisely as possible)?**
```
helm repo add aws-ebs-csi-driver https://kubernetes-sigs.github.io/aws-ebs-csi-driver
helm repo update

helm template aws-ebs-csi-driver \
    --namespace kube-system \
    aws-ebs-csi-driver/aws-ebs-csi-driver
```

Check the generated manifests, they would not have the namespace field.

**Anything else we need to know?**:

**Environment**
- Helm version (`version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}`):
- Driver version: **v1.1.0** (https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/CHANGELOG-0.x.md)

**Comment by krmichel** [comment]
That is generally how helm works. Most charts don't put the namespace in the template metadata. What is it that you are doing with the output of helm template that you need it to have the namespace explicitly in the manifests?

**Comment by tsunny** [comment]
I am adding few custom labels/annotations and few custom tolerations.

The current chart works fine for `helm install` but we do not use `helm install` in our pipeline.

**Comment by krmichel** [comment]
How do you apply the manifests? Kubectl or some other means?

**Comment by tsunny** [comment]
We use kubectl apply -f on the final manifests.

**Comment by krmichel** [comment]
Is there a reason that you can't add the `--namespace` flag to the `kubectl apply`?

**Comment by tsunny** [comment]
Sure. I can add that. But, the value that I am passing to the `helm template` command is ignored. My expectation was that I would set the namespace during manifest generation (because there is an option provided by helm to do that). However, the chart does not support this option. 

This is not a major bug but nice to have in the chart.

**Comment by krmichel** [comment]
It isn't ignored.  It is used in the role bindings.  I am hesitant to add the namespace to everything.  If we add it to all the resources and don't miss any then it would get you what you want.  My concern is in the future a new resource gets added and it not having a namespace gets missed in PR.  It wouldn't really matter to those doing `helm install/upgrade`  but for you, it would then cause the new resource to end up in the default namespace since it doesn't have a namespace on it.  @wongma7 what do you think about this?

Just out of curiosity what is your process in your pipeline that causes you to not want to use `helm install/upgrade`?

**Comment by wongma7** [comment]
This sounds like a helm issue, why does helm install/upgrade respect the --namespace tag but not helm template? https://github.com/helm/helm/issues/3553

IMO, leaving namespace blank is the least bad option even if it breaks this particular use-case. We arrived here with a lot of trial and  error, previously we did set namespace to something, so I am reluctant to now set `namespace: {{ .Release.Namespace }}` and potentially break another person's use-case.

**Comment by tsunny** [comment]
@krmichel -
1. We just don't use helm in the pipeline for historical reasons. And, it is beyond my control to change the pipelines we are using. And going down this path of discussion will not help solve this issue

2. "The namespace being ignored" might be wrong usage of terms. Sorry. The missing `{{ .Release.Namespace }}` in helm charts is what I was referring to. 

3. Regarding your concern about future resource missing the namespace field. Shouldn't the contributor and reviewers carefully make changes because these changes would affect many people who use this chart? 

@wongma7 - I did look at the helm issue before posting it here. They have closed it. And there have been many requests to reopen it. But no luck there.

**Comment by krmichel** [comment]
/kind feature
@tsunny 

1. I am just trying to help achieve your goal, but if you can't change the pipelines it makes it more difficult.  I assume since you say you can't change the pipelines, at least not much, that you wouldn't be able to use the kustomize manifests that are in the deploy/kubernetes directory of the repo to meet your needs?
2. I understand what you are trying to say is that you would like the manifests to have a namespace line when they are rendered from helm template.  I was just trying to convey that the behavior that is being seen isn't unusual or a bug based on the way helm is handling resources and namespaces.  They have chosen not to inject namespaces into the manifests for performance sake and to pass them at the API level instead.
3. I was not suggesting that the contributors/reviewers would be wantonly careless with their changes.  What I am saying is that they are human.  I contribute to a handful public charts and many private charts.  Many don't add the optional namespace to the metadata; some on purpose, some out of convenience, and likely some for lack of knowing how helm handles the charts.  There are some that I have contributed to that do add the namespace to the metadata.  Some do it because their charts can be configured to have resources in multiple namespaces and they can't solely rely on helm to take care of the namespace for them.  Some are currently in the inconsistent state that I mentioned, which doesn't cause issues with helm install/upgrade but would if someone was using helm template with another method of applying the manifests.  Again I don't believe that the individuals working on those charts made a conscious choice to make the chart behave strangely when used just as a template processor.  I will likely at some point miss this in a review or be the contributor and forget it.  I have certainly introduced bugs in my career as careful as I try to be.

In the end I just help maintain the chart and am not an owner in this repo, so the decision is not mine to make.  If someone were to make a PR to add the namespace metadata and could convince the owners to merge it I would review it carefully and try to do so moving forward as well.  They have been through a couple of itterations of messing with the namespace metadata and have most recently chosen to leave it out, but given your desired behavior maybe you or others wanting the same behavior can convince them it is worth doing.

**Comment by dghubble** [comment]
Helm has [declined](https://github.com/helm/helm/issues/3553) to provide a solution, so many charts have [started populating](https://github.com/istio/istio/pull/4606) the namespace to address this, as the OP is requesting. The use case is simply - those using `heml template` expect fully declarative manifests. While `kubectl` happens to have an imperative `-n foo` flag, there are other systems to apply manifests that expect fully declared manifests. Another reason might be simply that manifests checked into version control fully represent what's being deployed.
