### ISSUE TITLE
Snapshotter stateful chart does not consider tolerations

### ISSUE THREAD

**Issue by tsunny** [kubernetes-sigs/aws-ebs-csi-driver#951]
/kind bug

**What happened?**
The `Value.node.tolerateAllTaints` is not used by the [snapshotter template](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/snapshot-controller.yaml#L39).

As a result, if there is any taint on the node with `NoExecute` effect this will cause the snapshot controller to evicted from the node after 300 seconds.

**What you expected to happen?**
When the option `Value.node.tolerateAllTaints` is passed, it should be applied to snapshotter template too.

**How to reproduce it (as minimally and precisely as possible)?**
* Taint a node with NoExecute effect
* Execute 
   ```
    helm upgrade --install aws-ebs-csi-driver \
      --namespace kube-system --set node.tolerateAllTaints=true \
      aws-ebs-csi-driver/aws-ebs-csi-driver
    ```
* The snapshot controller statefulset will not have the below block
  ```
   tolerations:
      - operator: Exists
  ```

**Anything else we need to know?**:

**Environment**
- Helm version: `version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}`
- Driver version: v1.1.0

**Comment by krmichel** [comment]
The link you sent is to the controller and it uses [.Values.controller.tolerations](https://github.com/kubernetes-sigs/aws-ebs-csi-driver/blob/master/charts/aws-ebs-csi-driver/templates/controller.yaml#L47) to add additional tolerations if desired.  So, if you want you could add the `- operator: Exists` toleration in your values.  The controller is a deployment and generally, it doesn't make sense for a deployment to tolerate all taints.  It makes it difficult to drain a node when a pod for a deployment is terminated and potentially just reschedules on the draining node because it tolerates all taints including the scheduling disabled taint.

**Comment by krmichel** [comment]
The snapshot controller will likely no longer be installed by this chart since it isn't part of this project.  Related to issue #635

**Comment by krmichel** [comment]
Version 2.0.0 of the helm chart no longer installs the snapshot controller or its CRDs. The [snapshot controller](https://github.com/kubernetes-csi/external-snapshotter) is now listed as a pre-req if you want to use snapshot functionality. The enableVolumeSnapshot value no longer exists and the sidecar is enabled based on whether the snapshot API is available in the target cluster.
